"""empty message

Revision ID: a751b30e54df
Revises: 
Create Date: 2018-02-03 11:06:54.336404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a751b30e54df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('district', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('hallnum', sa.Integer(), nullable=True),
    sa.Column('servicecharge', sa.Float(), nullable=True),
    sa.Column('astrict', sa.Integer(), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('showName', sa.String(length=64), nullable=True),
    sa.Column('showNameEN', sa.String(length=64), nullable=True),
    sa.Column('director', sa.String(length=32), nullable=True),
    sa.Column('leadingRole', sa.String(length=256), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('screeningModel', sa.String(length=16), nullable=True),
    sa.Column('openDay', sa.Date(), nullable=True),
    sa.Column('backgroundPicture', sa.String(length=256), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('halls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cinemaID', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('screenType', sa.String(length=16), nullable=True),
    sa.Column('soundType', sa.String(length=16), nullable=True),
    sa.Column('seatNum', sa.Integer(), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cinemaID'], ['cinemas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hallschedulings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movieID', sa.Integer(), nullable=True),
    sa.Column('cinemaID', sa.Integer(), nullable=True),
    sa.Column('hallID', sa.Integer(), nullable=True),
    sa.Column('pressType', sa.Integer(), nullable=True),
    sa.Column('originalPrice', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('startTime', sa.Time(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('createTime', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('lastTime', sa.Time(), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cinemaID'], ['cinemas.id'], ),
    sa.ForeignKeyConstraint(['hallID'], ['halls.id'], ),
    sa.ForeignKeyConstraint(['movieID'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cinemaID', sa.Integer(), nullable=True),
    sa.Column('hallID', sa.Integer(), nullable=True),
    sa.Column('seatType', sa.Integer(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('isAllowSell', sa.Boolean(), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cinemaID'], ['cinemas.id'], ),
    sa.ForeignKeyConstraint(['hallID'], ['halls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('orderID', sa.String(length=128), nullable=False),
    sa.Column('movieID', sa.Integer(), nullable=True),
    sa.Column('cinemaID', sa.Integer(), nullable=True),
    sa.Column('hallID', sa.Integer(), nullable=True),
    sa.Column('hsID', sa.Integer(), nullable=True),
    sa.Column('seatIDStr', sa.String(length=128), nullable=True),
    sa.Column('ssIDStr', sa.String(length=128), nullable=True),
    sa.Column('qupiaoStr', sa.String(length=32), nullable=True),
    sa.Column('piaoNum', sa.Integer(), nullable=True),
    sa.Column('piaoPrice', sa.Float(), nullable=True),
    sa.Column('createTime', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('payTime', sa.Time(), nullable=True),
    sa.Column('getTime', sa.Time(), nullable=True),
    sa.Column('tuikuanTime', sa.Time(), nullable=True),
    sa.Column('lastTime', sa.Time(), nullable=True),
    sa.Column('flag', sa.Integer(), nullable=True),
    sa.Column('isDelete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cinemaID'], ['cinemas.id'], ),
    sa.ForeignKeyConstraint(['hallID'], ['halls.id'], ),
    sa.ForeignKeyConstraint(['hsID'], ['hallschedulings.id'], ),
    sa.ForeignKeyConstraint(['movieID'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('orderID')
    )
    op.create_table('seatschedulings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cinemaID', sa.Integer(), nullable=True),
    sa.Column('hallID', sa.Integer(), nullable=True),
    sa.Column('seatID', sa.Integer(), nullable=True),
    sa.Column('hsID', sa.Integer(), nullable=True),
    sa.Column('orderID', sa.String(length=128), nullable=True),
    sa.Column('createTime', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['cinemaID'], ['cinemas.id'], ),
    sa.ForeignKeyConstraint(['hallID'], ['halls.id'], ),
    sa.ForeignKeyConstraint(['hsID'], ['hallschedulings.id'], ),
    sa.ForeignKeyConstraint(['orderID'], ['orders.orderID'], ),
    sa.ForeignKeyConstraint(['seatID'], ['seats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seatschedulings')
    op.drop_table('orders')
    op.drop_table('seats')
    op.drop_table('hallschedulings')
    op.drop_table('halls')
    op.drop_table('movies')
    op.drop_table('cinemas')
    # ### end Alembic commands ###
